### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by misioq23** [misioq23/boilerplate#1]
- [ ] Add test framework
- [ ] Add rollup uglify
- [ ] Add production mode
- [ ] Add image build
